# Cloud Build configuration for TCV Video QC Analyzer
# Automatically builds and deploys to Cloud Run on push
# Uses async processing architecture for reliable large file handling

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tcv-video-analyzer'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '10'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      # Startup CPU boost for faster cold starts
      - '--startup-cpu-boost'
      # Startup probe configuration - ensures container is healthy before receiving traffic
      - '--startup-probe-path=/startup'
      - '--startup-probe-initial-delay=0'
      - '--startup-probe-period=10'
      - '--startup-probe-failure-threshold=3'
      - '--startup-probe-timeout=5'
      # Liveness probe - keeps container healthy during background processing
      - '--liveness-probe-path=/health'
      - '--liveness-probe-period=30'
      - '--liveness-probe-failure-threshold=3'
      - '--liveness-probe-timeout=5'
      # Service account for GCS/Vertex AI access
      - '--service-account'
      - 'tcv-analyzer@${PROJECT_ID}.iam.gserviceaccount.com'
      # Environment variables
      - '--set-env-vars'
      - 'GCS_BUCKET=${_GCS_BUCKET},SUPABASE_URL=${_SUPABASE_URL}'
      - '--set-secrets'
      - 'GCP_CALLBACK_SECRET=GCP_CALLBACK_SECRET:latest'
      - '--allow-unauthenticated'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tcv-video-analyzer:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY

# Substitution variables (set these in Cloud Build trigger)
substitutions:
  _GCS_BUCKET: 'tcvstudioanalyze'
  _SUPABASE_URL: 'https://hdytpmbgrhaxyjvvpewy.supabase.co'
